puts "Creating admin user......."

banfox = Seller.create!(
  full_name: "joaquim de oliveira neto",
  cpf: "09670133645",
  rf_full_name: "joaquim de oliveira neto",
  rf_sit_cad: "regular",
  birth_date: "21041989",
  mobile: "11998308090",
  company_name: "banfox s.a.",
  company_nickname: "banfox",
  cnpj: "23198636000195",
  phone: "11938008131",
  website: "www.banfox.com.br",
  address: "av vergueiro",
  address_number: "1061",
  address_comp: "",
  neighborhood: "liberdade",
  state: "sp",
  city: "são paulo",
  zip_code: "04552000",
  inscr_est: "",
  inscr_mun: "",
  nire: "",
  company_type: "sa",
  operation_limit_cents: 30000000,
  operation_limit_currency: "BRL",
  fator: 0.039,
  advalorem: 0.001,
  protection: 0.2,
  monthly_revenue_cents: 50000000,
  monthly_revenue_currency: "BRL",
  monthly_fixed_cost_cents: 35000000,
  monthly_fixed_cost_currency: "BRL",
  monthly_units_sold: 10500,
  cost_per_unit_cents: 3300,
  cost_per_unit_currency: "BRL",
  debt_cents: 3800000,
  debt_currency: "BRL",
  full_name_partner: "joaquim de oliveira neto",
  cpf_partner: "09670133645",
  rf_full_name_partner: "joaquim de oliveira neto",
  rf_sit_cad_partner: "regular",
  birth_date_partner: "21041989",
  mobile_partner: "11998308090",
  email_partner: "joaquim@banfox.com.br",
  consent: true,
  validation_status: "active",
  visited: true,
  analysis_status: "approved",
  rejection_motive: "rejection_motive_non_applicable",
)

banfox_user = User.create!(
  email: "joaquim@banfox.com.br",
  password: Rails.application.credentials[:banfox_main_app][:admin_default_password],
  admin: true,
  seller: banfox
)

