puts "Creating Shop Joss..........."

shopjoss = Seller.create!(
  full_name: "jose carlos pereira de souza marra",
  cpf: "21869357833",
  rf_full_name: "jose carlos pereira de souza marra",
  rf_sit_cad: "regular",
  birth_date: "11011981",
  mobile: "13997727575",
  company_name: "jose carlos pereira de souza marra me",
  company_nickname: "shop joss",
  cnpj: "18511737000134",
  phone: "1332883550",
  website: "www.shopjoss.com.br",
  address: "rua da paz",
  address_number: "53",
  address_comp: "",
  neighborhood: "boqueirão",
  state: "sp",
  city: "santos",
  zip_code: "11045520",
  inscr_est: "",
  inscr_mun: "",
  nire: "",
  company_type: "me",
  operation_limit_cents: 20000000,
  operation_limit_currency: "BRL",
  fator: 0.049,
  advalorem: 0.001,
  monthly_revenue_cents: 34000000,
  monthly_revenue_currency: "BRL",
  monthly_fixed_cost_cents: 5500000,
  monthly_fixed_cost_currency: "BRL",
  monthly_units_sold: 12000,
  cost_per_unit_cents: 800,
  cost_per_unit_currency: "BRL",
  debt_cents: 2000000,
  debt_currency: "BRL",
  full_name_partner: "jose carlos pereira de souza marra",
  cpf_partner: "21869357833",
  rf_full_name_partner: "jose carlos pereira de souza marra",
  rf_sit_cad_partner: "regular",
  birth_date_partner: "11011981",
  mobile_partner: "13997727575",
  email_partner: "financeiro@shopjoss.com.br",
  consent: true,
  validation_status: "active",
  visited: true,
  analysis_status: "approved",
  rejection_motive: "non_applicable",
  protection: 0.2,
)

shopjoss_user = User.create!(
  email: "financeiro@shopjoss.com.br",
  password: "shopjoss"
  admin: false,
  seller: shopjoss,
)
