daily_check:
  cron: "0 13 * * 1-5"
  class: "BillingRulerCron"

monthly_organization_check:
  cron: "0 13 1 * *"
  class: "MonthlyOrganizationCron"

#weekly_organization_check:
#  cron: "0 13 * * 1"
#  class: "WeeklyOrganizationCron"
