daily_check:
  cron: "0 12 * * *"
  class: "BillingRulerCron"

monthly_organization_check:
  cron: "0 12 1 * *"
  class: "MonthlyOrganizationCron"

weekly_organization_check:
  cron: "0 12 * * 0"
  class: "WeeklyOrganizationCron"
