monthly_organization_check:
  cron: "0 13 1 * *"
  class: "MonthlyOrganizationCron"

#weekly_organization_check:
#  cron: "0 13 * * 1"
#  class: "WeeklyOrganizationCron"

due_date_check:
  cron: "0 13 * * 1-5"
  class: "DueDateCron"

just_overdued_check:
  cron: "0 13 * * 1-5"
  class: "JustOverduedCron"

overdue_check:
  cron: "0 13 * * 1-5"
  class: "OverdueCron"

overdue_pre_serasa_check:
  cron: "0 13 * * 1-5"
  class: "OverduePreSerasaCron"

sending_to_serasa_check:
  cron: "0 13 * * 1-5"
  class: "SendingToSerasaCron"

overdue_after_serasa_check:
  cron: "0 13 * * 1-5"
  class: "OverdueAfterSerasaCron"

protest_check:
  cron: "0 13 * * 1-5"
  class: "ProtestCron"
