local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
  # host: "http://localhost:3000"

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

amazon:
  service: S3
  access_key_id: <%= Rails.application.credentials.production[:aws][:access_key_id] %>
  secret_access_key: <%= Rails.application.credentials.production[:aws][:secret_access_key] %>
  region: <%= Rails.application.credentials.production[:aws][:region] %>
  bucket: <%= Rails.application.credentials.production[:aws][:bucket] %>
