import "bootstrap";
import { selectTagOnClick } from "../components/wizard";
import { sliderShowValue } from "../components/slider";
import { maskCpfAndCnpj } from "../components/formMask";
import { nameFilesToUpload } from "../components/filesUpload";
import { animateNavbar } from "../components/newnavbar";
import { showPage } from "../components/homeAnimation";
import { loop } from "../components/showOnScroll";
loop();
showPage();
selectTagOnClick();
sliderShowValue();
maskCpfAndCnpj();
nameFilesToUpload();
animateNavbar();
